[package]
name = "ingest_app"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.27", features = ["persistence"] }
directories = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.35"
fs_extra = "1.3"
image = "0.24"
